name: Notion Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天上午 3 点运行

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  notion_sync:
    name: Notion Sync
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      REF: ${{ github.ref }}
      REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug repository structure
        run: |
          pwd
          ls -R

      - name: Notion data sync
        run: |
          python src/notion.py
